const { chromium } = require('C:/Users/淮青/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
(async () => {
  const out = path.join(__dirname, '../logs/visual-qa');
  fs.mkdirSync(out, { recursive: true });
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:4174/#home');
  await page.locator('.intro-cover img').evaluate(img => img.decode());
  assert.equal(await page.locator('.intro-cover').evaluate(el => getComputedStyle(el, '::before').content), 'none');
  assert.equal(await page.locator('.intro-cover img').evaluate(el => getComputedStyle(el).filter), 'none');
  const cover = await page.locator('.intro-cover').boundingBox();
  const cta = await page.locator('.intro-cover-cta').boundingBox();
  assert.ok(cta.y >= cover.y + cover.height, 'CTA must be outside cover');
  await page.screenshot({ path: path.join(out, 'cover-desktop.png') });
  await page.locator('.intro-cover-cta').click();
  await page.locator('.intro-overlay.story').waitFor();
  await page.evaluate(() => document.fonts.load('32px "Zhi Mang Xing"', '风从湿地醒来'));
  const title = await page.locator('.story-film-title h2').evaluate(el => ({ family: getComputedStyle(el).fontFamily, gradient: getComputedStyle(el).backgroundImage, loaded: [...document.fonts].some(f => f.family === 'Zhi Mang Xing' && f.status === 'loaded') }));
  assert.ok(title.loaded);
  assert.ok(title.family.includes('Zhi Mang Xing'));
  assert.ok(title.gradient.includes('255, 229, 153'));
  await page.waitForTimeout(800);
  await page.screenshot({ path: path.join(out, 'story-desktop.png') });
  await page.locator('.intro-overlay.products').waitFor({ timeout: 16000 });
  await page.locator('.film-controls button').nth(1).click();
  await page.waitForFunction(() => document.querySelector('.film-controls button:nth-child(2)').getAttribute('aria-selected') === 'true');
  await page.locator('.intro-overlay').waitFor({ state: 'detached', timeout: 15000 });
  assert.notEqual(await page.evaluate(() => document.body.style.overflow), 'hidden');
  assert.equal(await page.locator('.site-header nav a').count(), 6);
  for (const viewport of [{ width: 390, height: 844 }, { width: 844, height: 390 }]) {
    await page.setViewportSize(viewport);
    await page.reload();
    await page.locator('.intro-cover img').evaluate(img => img.decode());
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: path.join(out, `cover-${viewport.width}.png`) });
    await page.locator('.intro-cover-cta').click();
    await page.waitForTimeout(800);
    await page.screenshot({ path: path.join(out, `story-${viewport.width}.png`) });
    await page.keyboard.press('Escape');
    await page.locator('.intro-overlay').waitFor({ state: 'detached' });
    assert.notEqual(await page.evaluate(() => document.body.style.overflow), 'hidden');
  }
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.reload();
  await page.locator('.intro-skip').click();
  await page.locator('.intro-overlay').waitFor({ state: 'detached' });
  assert.deepEqual(errors, []);
  console.log('Opening QA passed: cover, local gold font, sequence, chapters, skip, Escape, scrolling, mobile, reduced motion.');
  console.log(title);
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
